export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const SIGNOUT = 'SIGNOUT'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const GET_TEMPLATES = 'GET_TEMPLATES'
export const GET_TEMPLATE = 'GET_TEMPLATE'
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const ERROR_TEMPLATE = 'ERROR_TEMPLATE'